_recursive_: false
_target_: climsr.core.task.TaskSuperResolutionModule

generator: ${generator}
discriminator: ${discriminator}
optimizers: ${optimizers}
schedulers: ${schedulers}

initial_hp_metric_val: 5e-3
