# -*- coding: utf-8 -*-
lr = "lr"
hr = "hr"
elevation = "elevation"
mask = "mask"
elevation_lr = "elevation_lr"
nearest = "nearest"
cubic = "cubic"
original_data = "original_data"
mask_np = "mask_np"
min = "min"
max = "max"
filename = "filename"
normalized = "normalized"
standardized = "standardized"
