# -*- coding: utf-8 -*-
hr = "HR"
lr = "LR"
sr = "SR"
hr_images = "HR Images"
lr_images = "LR Images"
sr_images = "SR Images"
elevation = "Elevation"
cubic_interpolation = "Cubic Interpolation"
nearest_interpolation = "Nearest Interpolation"
