# -*- coding: utf-8 -*-
hr = "HR"
lr = "LR"
sr = "SR"
hr_images = "HR Images"
lr_images = "LR Images"
sr_images = "SR Images"
elevation = "Elevation"
cubic_interpolation = "Interp. Cubic"
nearest_interpolation = "Interp. Nearest"
mask = "Land Mask"
error = "SR Error"
