# -*- coding: utf-8 -*-
mean = "mean"
min = "min"
max = "max"
global_min = "global_min"
global_max = "global_max"
std = "std"
normalized_min = "normalized_min"
normalized_max = "normalized_max"
nan_sub = "nan_sub"
