name: climsr
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - pytorch=1.10.0
  - torchvision>0.11.0
  - cudatoolkit=11.3
  - geopandas
  - dask
  - xarray
  - rioxarray
  - cartopy
  - rasterio
  - netCDF4
  - pip
  - pip:
      - jupyterlab
      - scikit-learn
      - pytorch-lightning
      - albumentations
      - transformers
      - pyarrow==5.0.0
      - seaborn
      - isort==5.8.0
      - black==20.8b1
      - flake8==3.9.0
      - pytest==6.2.3
      - pytest_cases==3.6.3
      - pre-commit==2.12.0
      - beautifulsoup4==4.9.3
      - hydra-core==1.1.0
      - hydra-colorlog==1.1.0
      - hydra-optuna-sweeper==1.1.0
      - rich==10.15.2
