name: climsr
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.1
  - geopandas
  - dask
  - xarray
  - rioxarray
  - cartopy
  - datacube
  - rasterio
  - netCDF4
  - pip
  - pip:
      - jupyterlab==3.0.14
      - scikit-learn==0.24.1
      - pytorch-lightning==1.4.6
      - albumentations==1.0.3
      - transformers==4.10.2
      - pyarrow==5.0.0
      - seaborn==0.11.1
      - isort==5.8.0
      - black==20.8b1
      - flake8==3.9.0
      - pytest==6.2.3
      - pytest_cases==3.6.3
      - pre-commit==2.12.0
      - beautifulsoup4==4.9.3
      - hydra-core==1.1.1
