name: sr
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - cudatoolkit=11.0
  - pytorch-lightning
  - pytorch
  - torchvision
  - geopandas
  - dask
  - basemap
  - xarray
  - rioxarray
  - cartopy
  - datacube
  - pip
  - pip:
      - jupyterlab
      - scikit-learn
      - seaborn
      - netCDF4
      - rasterio
      - rio-tiler
      - isort
      - black
      - flake8
      - pytest
      - pre-commit
