# @package dataset
defaults:
  - nlp/default
_target_: climsr.core.data.SuperResolutionDataModule
cfg:
  dataset_name: xnli
   # ['ar', 'bg', 'de', 'el', 'en', 'es', 'fr', 'hi', 'ru', 'sw', 'th', 'tr', 'ur', 'vi', 'zh', 'all_languages']
  dataset_config_name: en
