# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "logs"
  name: ${training.experiment_name}
  version: null
  log_graph: False
  default_hp_metric: False
  prefix: ""
