defaults:
  - _self_
  - task: gan_training
  - callbacks:
    - early_stopping
    - gpu_stats_monitor
    - learning_rate_monitor
    - model_checkpoint
    - learning_rate_monitor
    - log_images
  - datamodule: super_resolution_data_module
  - discriminator: ???
  - logger: tensorboard
  - generator: ???
  - optimizers: default
  - schedulers: default
  - trainer: default
  - training: default
  - hydra: default

  - experiment: srcnn_pre_training

log: False
ignore_warnings: True
