defaults:
  - callbacks:
      - early_stopping
      - model_checkpoint
      - log_images
  - datamodule: super_resolution_data_module
  - discriminator: ???
  - logger: tensorboard
  - model: ???
  - optimizer: adamw
  - scheduler: one_cycle_schedule
  - task: gan_training
  - trainer: default
  - training: default

  - experiment: esrgan_training

log: False
ignore_warnings: True
