defaults:
  - task: gan_training
  - callbacks:
      - early_stopping
      - model_checkpoint
      - log_images
  - datamodule: super_resolution_data_module
  - discriminator: ???
  - logger: tensorboard
  - generator: ???
  - optimizers: ???
  - schedulers: ???
  - trainer: default
  - training: default

  - experiment: rcan_final

log: False
ignore_warnings: True
