defaults:
  - _self_
  - task: gan_training
  - callbacks:
    - early_stopping
    - gpu_stats_monitor
    - learning_rate_monitor
    - model_checkpoint
    - learning_rate_monitor
    - log_images
  - datamodule: super_resolution_data_module
  - discriminator: ???
  - logger: tensorboard
  - generator: ???
  - optimizers: default
  - schedulers: default
  - trainer: default
  - training: default
  - profiler: null

  - experiment: ???

  - hydra: default
  - hparams_search: null

  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

log: False
ignore_warnings: True
print_config: True
