data_dir_cruts: "/media/xultaeculcis/2TB/datasets/cruts/original/"
data_dir_world_clim: "/media/xultaeculcis/2TB/datasets/wc/weather/"
out_dir_cruts: "/media/xultaeculcis/2TB/datasets/cruts/pre-processed"
out_dir_world_clim: "/media/xultaeculcis/2TB/datasets/wc/pre-processed"

world_clim_elevation_fp: "/media/xultaeculcis/2TB/datasets/wc/elevation/wc2.1_2.5m_elev.tif"
dataframe_output_path: "../../datasets/"
elevation_file: "/media/xultaeculcis/2TB/datasets/wc/pre-processed/elevation/resized/4x/wc2.1_2.5m_elev.tif"
land_mask_file: "/media/xultaeculcis/2TB/datasets/wc/pre-processed/prec/resized/4x/wc2.1_2.5m_prec_1961-01.tif"

run_cruts_to_cog: True
run_temp_rasters_generation: True
run_statistics_computation: True
run_world_clim_resize: True
run_world_clim_tiling: True
run_world_clim_elevation_resize: True
run_train_val_test_split: True
run_extent_extraction: True
run_z_score_stats_computation: True
run_min_max_stats_computation: True

patch_size: [128, 128]
patch_stride: 64
normalize_patches: False
n_workers: 8
threads_per_worker: 1
res_mult_inx: 2

train_years: [1961, 2004]
val_years: [2005, 2017]
test_years: [2018, 2019]
