early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/rmse" # name of the logged metric which determines when model is improving
  mode: "min" # can be "max" or "min"
  patience: 100 # how many epochs of not improving until training stops
  min_delta: 0 # minimum change in the monitored metric needed to qualify as an improvement
