gpu_stats_monitor:
  _target_: pytorch_lightning.callbacks.GPUStatsMonitor
  memory_utilization: True
  gpu_utilization: True
  intra_step_time: True
  inter_step_time: True
  fan_speed: True
  temperature: True
