_target_: climsr.data.super_resolution_data_module.SuperResolutionDataModule
cfg:
  batch_size: ${training.batch_size}
  validation_batch_size: ${training.validation_batch_size}
  num_workers: ${training.num_workers}
  pin_memory: True
  data_path: "datasets"
  europe_extent: False
  world_clim_variable: "temp"
  resolutions:
    - "10m"
    - "5m"
    - "2.5m"
  generator_type: "rcan"
  scale_factor: 4
  seed: ${training.seed}
  normalization_method: "minmax"
  normalization_range: [-1.0, 1.0]
  use_elevation: True
  use_mask: True
  use_global_min_max: True
  transforms:
    v_flip: True
    h_flip: True
    random_90_rotation: True
